version: '3.7'

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8081:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
      - source: hapi-extra-classes
        target: /app/extra-classes
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
       - fhir_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  fhir_data:
    external: true

configs:
  hapi:
     file: ./hapi.application.yaml
  hapi-extra-classes:
      file: ./hapi-extra-classes